# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-f49bebbd-7527-45f2-b803-6de3a0b0a680";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-f49bebbd-7527-45f2-b803-6de3a0b0a680".device = "/dev/disk/by-uuid/f49bebbd-7527-45f2-b803-6de3a0b0a680";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/EC2A-2714";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-4d8efd9c-86f7-4d54-b70a-d3914f002ad8"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
